require("config.options")
require("config.keymaps")
require("config.autocmds")

require("plugins.lsp")
require("plugins.treesitter")
require("plugins.mini")
require("plugins.luasnip")
require("plugins.cmp")
require("plugins.latex")
